export const OBTENER10OPERACIONES = 'OBTENER10OPERACIONES';
export const OBTENEROPERACIONES = 'OBTENEROPERACIONES';
export const SELECCIONAROPERACION = 'SELECCIONAROPERACION';
export const ELIMINAROPERACION = 'ELIMINAROPERACION';
export const CREAROPERACION = 'CREAROPERACION';
export const MODIFICAROPERACION = 'MODIFICAROPERACION';
export const OBTENERBALANCE = 'OBTENERBALANCE';
export const OBTENERCATEGORIAS = 'OBTENERCATEGORIAS';

export const MOSTRARALERTA = 'MOSTRARALERTA'
export const OCULTARALERTA = 'OCULTARALERTA';

export const INICIAR_SESION = 'INICIAR_SESION';
export const CERRAR_SESION = 'CERRAR_SESION';
export const LOGUEO_ERROR = 'LOGUEO_ERROR';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
